/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatIsAranciniRouteImport } from './routes/what-is-arancini'
import { Route as SamarbeidRouteImport } from './routes/samarbeid'
import { Route as NextPopupRouteImport } from './routes/next-popup'
import { Route as ForBarerRouteImport } from './routes/for-barer'
import { Route as EnRouteImport } from './routes/en'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as EnWhatIsAranciniRouteImport } from './routes/en.what-is-arancini'
import { Route as EnNextPopupRouteImport } from './routes/en.next-popup'
import { Route as EnCollaborateRouteImport } from './routes/en.collaborate'
import { Route as EnAboutRouteImport } from './routes/en.about'
import { Route as AdminPopupRouteImport } from './routes/admin/popup'
import { Route as AdminNewsletterRouteImport } from './routes/admin/newsletter'
import { Route as AdminInquiriesRouteImport } from './routes/admin/inquiries'
import { Route as AdminAccountingRouteImport } from './routes/admin/accounting'
import { Route as AdminSlugRouteImport } from './routes/admin/$slug'

const WhatIsAranciniRoute = WhatIsAranciniRouteImport.update({
  id: '/what-is-arancini',
  path: '/what-is-arancini',
  getParentRoute: () => rootRouteImport,
} as any)
const SamarbeidRoute = SamarbeidRouteImport.update({
  id: '/samarbeid',
  path: '/samarbeid',
  getParentRoute: () => rootRouteImport,
} as any)
const NextPopupRoute = NextPopupRouteImport.update({
  id: '/next-popup',
  path: '/next-popup',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBarerRoute = ForBarerRouteImport.update({
  id: '/for-barer',
  path: '/for-barer',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EnWhatIsAranciniRoute = EnWhatIsAranciniRouteImport.update({
  id: '/what-is-arancini',
  path: '/what-is-arancini',
  getParentRoute: () => EnRoute,
} as any)
const EnNextPopupRoute = EnNextPopupRouteImport.update({
  id: '/next-popup',
  path: '/next-popup',
  getParentRoute: () => EnRoute,
} as any)
const EnCollaborateRoute = EnCollaborateRouteImport.update({
  id: '/collaborate',
  path: '/collaborate',
  getParentRoute: () => EnRoute,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => EnRoute,
} as any)
const AdminPopupRoute = AdminPopupRouteImport.update({
  id: '/popup',
  path: '/popup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountingRoute = AdminAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSlugRoute = AdminSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/en': typeof EnRouteWithChildren
  '/for-barer': typeof ForBarerRoute
  '/next-popup': typeof NextPopupRoute
  '/samarbeid': typeof SamarbeidRoute
  '/what-is-arancini': typeof WhatIsAranciniRoute
  '/admin/$slug': typeof AdminSlugRoute
  '/admin/accounting': typeof AdminAccountingRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/popup': typeof AdminPopupRoute
  '/en/about': typeof EnAboutRoute
  '/en/collaborate': typeof EnCollaborateRoute
  '/en/next-popup': typeof EnNextPopupRoute
  '/en/what-is-arancini': typeof EnWhatIsAranciniRoute
  '/admin/': typeof AdminIndexRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/for-barer': typeof ForBarerRoute
  '/next-popup': typeof NextPopupRoute
  '/samarbeid': typeof SamarbeidRoute
  '/what-is-arancini': typeof WhatIsAranciniRoute
  '/admin/$slug': typeof AdminSlugRoute
  '/admin/accounting': typeof AdminAccountingRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/popup': typeof AdminPopupRoute
  '/en/about': typeof EnAboutRoute
  '/en/collaborate': typeof EnCollaborateRoute
  '/en/next-popup': typeof EnNextPopupRoute
  '/en/what-is-arancini': typeof EnWhatIsAranciniRoute
  '/admin': typeof AdminIndexRoute
  '/en': typeof EnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/en': typeof EnRouteWithChildren
  '/for-barer': typeof ForBarerRoute
  '/next-popup': typeof NextPopupRoute
  '/samarbeid': typeof SamarbeidRoute
  '/what-is-arancini': typeof WhatIsAranciniRoute
  '/admin/$slug': typeof AdminSlugRoute
  '/admin/accounting': typeof AdminAccountingRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/popup': typeof AdminPopupRoute
  '/en/about': typeof EnAboutRoute
  '/en/collaborate': typeof EnCollaborateRoute
  '/en/next-popup': typeof EnNextPopupRoute
  '/en/what-is-arancini': typeof EnWhatIsAranciniRoute
  '/admin/': typeof AdminIndexRoute
  '/en/': typeof EnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/en'
    | '/for-barer'
    | '/next-popup'
    | '/samarbeid'
    | '/what-is-arancini'
    | '/admin/$slug'
    | '/admin/accounting'
    | '/admin/inquiries'
    | '/admin/newsletter'
    | '/admin/popup'
    | '/en/about'
    | '/en/collaborate'
    | '/en/next-popup'
    | '/en/what-is-arancini'
    | '/admin/'
    | '/en/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/for-barer'
    | '/next-popup'
    | '/samarbeid'
    | '/what-is-arancini'
    | '/admin/$slug'
    | '/admin/accounting'
    | '/admin/inquiries'
    | '/admin/newsletter'
    | '/admin/popup'
    | '/en/about'
    | '/en/collaborate'
    | '/en/next-popup'
    | '/en/what-is-arancini'
    | '/admin'
    | '/en'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/en'
    | '/for-barer'
    | '/next-popup'
    | '/samarbeid'
    | '/what-is-arancini'
    | '/admin/$slug'
    | '/admin/accounting'
    | '/admin/inquiries'
    | '/admin/newsletter'
    | '/admin/popup'
    | '/en/about'
    | '/en/collaborate'
    | '/en/next-popup'
    | '/en/what-is-arancini'
    | '/admin/'
    | '/en/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  EnRoute: typeof EnRouteWithChildren
  ForBarerRoute: typeof ForBarerRoute
  NextPopupRoute: typeof NextPopupRoute
  SamarbeidRoute: typeof SamarbeidRoute
  WhatIsAranciniRoute: typeof WhatIsAranciniRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-is-arancini': {
      id: '/what-is-arancini'
      path: '/what-is-arancini'
      fullPath: '/what-is-arancini'
      preLoaderRoute: typeof WhatIsAranciniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samarbeid': {
      id: '/samarbeid'
      path: '/samarbeid'
      fullPath: '/samarbeid'
      preLoaderRoute: typeof SamarbeidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-barer': {
      id: '/for-barer'
      path: '/for-barer'
      fullPath: '/for-barer'
      preLoaderRoute: typeof ForBarerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next-popup': {
      id: '/next-popup'
      path: '/next-popup'
      fullPath: '/next-popup'
      preLoaderRoute: typeof NextPopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/en/what-is-arancini': {
      id: '/en/what-is-arancini'
      path: '/what-is-arancini'
      fullPath: '/en/what-is-arancini'
      preLoaderRoute: typeof EnWhatIsAranciniRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/next-popup': {
      id: '/en/next-popup'
      path: '/next-popup'
      fullPath: '/en/next-popup'
      preLoaderRoute: typeof EnNextPopupRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/collaborate': {
      id: '/en/collaborate'
      path: '/collaborate'
      fullPath: '/en/collaborate'
      preLoaderRoute: typeof EnCollaborateRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/about': {
      id: '/en/about'
      path: '/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof EnRoute
    }
    '/admin/popup': {
      id: '/admin/popup'
      path: '/popup'
      fullPath: '/admin/popup'
      preLoaderRoute: typeof AdminPopupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounting': {
      id: '/admin/accounting'
      path: '/accounting'
      fullPath: '/admin/accounting'
      preLoaderRoute: typeof AdminAccountingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$slug': {
      id: '/admin/$slug'
      path: '/$slug'
      fullPath: '/admin/$slug'
      preLoaderRoute: typeof AdminSlugRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSlugRoute: typeof AdminSlugRoute
  AdminAccountingRoute: typeof AdminAccountingRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminPopupRoute: typeof AdminPopupRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSlugRoute: AdminSlugRoute,
  AdminAccountingRoute: AdminAccountingRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminPopupRoute: AdminPopupRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EnRouteChildren {
  EnAboutRoute: typeof EnAboutRoute
  EnCollaborateRoute: typeof EnCollaborateRoute
  EnNextPopupRoute: typeof EnNextPopupRoute
  EnWhatIsAranciniRoute: typeof EnWhatIsAranciniRoute
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnAboutRoute: EnAboutRoute,
  EnCollaborateRoute: EnCollaborateRoute,
  EnNextPopupRoute: EnNextPopupRoute,
  EnWhatIsAranciniRoute: EnWhatIsAranciniRoute,
  EnIndexRoute: EnIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  EnRoute: EnRouteWithChildren,
  ForBarerRoute: ForBarerRoute,
  NextPopupRoute: NextPopupRoute,
  SamarbeidRoute: SamarbeidRoute,
  WhatIsAranciniRoute: WhatIsAranciniRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
