/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatIsAranciniRouteImport } from './routes/what-is-arancini'
import { Route as NextPopupRouteImport } from './routes/next-popup'
import { Route as EnRouteImport } from './routes/en'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as EnWhatIsAranciniRouteImport } from './routes/en.what-is-arancini'
import { Route as EnNextPopupRouteImport } from './routes/en.next-popup'
import { Route as EnAboutRouteImport } from './routes/en.about'
import { Route as AdminSlugRouteImport } from './routes/admin/$slug'

const WhatIsAranciniRoute = WhatIsAranciniRouteImport.update({
  id: '/what-is-arancini',
  path: '/what-is-arancini',
  getParentRoute: () => rootRouteImport,
} as any)
const NextPopupRoute = NextPopupRouteImport.update({
  id: '/next-popup',
  path: '/next-popup',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EnWhatIsAranciniRoute = EnWhatIsAranciniRouteImport.update({
  id: '/what-is-arancini',
  path: '/what-is-arancini',
  getParentRoute: () => EnRoute,
} as any)
const EnNextPopupRoute = EnNextPopupRouteImport.update({
  id: '/next-popup',
  path: '/next-popup',
  getParentRoute: () => EnRoute,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => EnRoute,
} as any)
const AdminSlugRoute = AdminSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/en': typeof EnRouteWithChildren
  '/next-popup': typeof NextPopupRoute
  '/what-is-arancini': typeof WhatIsAranciniRoute
  '/admin/$slug': typeof AdminSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/next-popup': typeof EnNextPopupRoute
  '/en/what-is-arancini': typeof EnWhatIsAranciniRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/en': typeof EnRouteWithChildren
  '/next-popup': typeof NextPopupRoute
  '/what-is-arancini': typeof WhatIsAranciniRoute
  '/admin/$slug': typeof AdminSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/next-popup': typeof EnNextPopupRoute
  '/en/what-is-arancini': typeof EnWhatIsAranciniRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/en': typeof EnRouteWithChildren
  '/next-popup': typeof NextPopupRoute
  '/what-is-arancini': typeof WhatIsAranciniRoute
  '/admin/$slug': typeof AdminSlugRoute
  '/en/about': typeof EnAboutRoute
  '/en/next-popup': typeof EnNextPopupRoute
  '/en/what-is-arancini': typeof EnWhatIsAranciniRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/en'
    | '/next-popup'
    | '/what-is-arancini'
    | '/admin/$slug'
    | '/en/about'
    | '/en/next-popup'
    | '/en/what-is-arancini'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/en'
    | '/next-popup'
    | '/what-is-arancini'
    | '/admin/$slug'
    | '/en/about'
    | '/en/next-popup'
    | '/en/what-is-arancini'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/en'
    | '/next-popup'
    | '/what-is-arancini'
    | '/admin/$slug'
    | '/en/about'
    | '/en/next-popup'
    | '/en/what-is-arancini'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  EnRoute: typeof EnRouteWithChildren
  NextPopupRoute: typeof NextPopupRoute
  WhatIsAranciniRoute: typeof WhatIsAranciniRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-is-arancini': {
      id: '/what-is-arancini'
      path: '/what-is-arancini'
      fullPath: '/what-is-arancini'
      preLoaderRoute: typeof WhatIsAranciniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next-popup': {
      id: '/next-popup'
      path: '/next-popup'
      fullPath: '/next-popup'
      preLoaderRoute: typeof NextPopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/en/what-is-arancini': {
      id: '/en/what-is-arancini'
      path: '/what-is-arancini'
      fullPath: '/en/what-is-arancini'
      preLoaderRoute: typeof EnWhatIsAranciniRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/next-popup': {
      id: '/en/next-popup'
      path: '/next-popup'
      fullPath: '/en/next-popup'
      preLoaderRoute: typeof EnNextPopupRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/about': {
      id: '/en/about'
      path: '/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof EnRoute
    }
    '/admin/$slug': {
      id: '/admin/$slug'
      path: '/$slug'
      fullPath: '/admin/$slug'
      preLoaderRoute: typeof AdminSlugRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSlugRoute: typeof AdminSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSlugRoute: AdminSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EnRouteChildren {
  EnAboutRoute: typeof EnAboutRoute
  EnNextPopupRoute: typeof EnNextPopupRoute
  EnWhatIsAranciniRoute: typeof EnWhatIsAranciniRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnAboutRoute: EnAboutRoute,
  EnNextPopupRoute: EnNextPopupRoute,
  EnWhatIsAranciniRoute: EnWhatIsAranciniRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  EnRoute: EnRouteWithChildren,
  NextPopupRoute: NextPopupRoute,
  WhatIsAranciniRoute: WhatIsAranciniRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
